---
title: "Visualizing Time"
author: "Ben Goldstone"
date: "10/20/2023"
output: 
  pdf_document:
    fig_height: 3
    fig_width: 5
  html_document:
    fig_height: 3
    fig_width: 5
  word_document:
    fig_height: 3
    fig_width: 5
---

```{r, setup, include=FALSE}
require(mosaic)    # Load additional packages here 
require(ggformula) # formula interface to ggplot2
require(Stat2Data)
require(Lock5Data)
require(tidyr)
# Some customization.  You can alter or delete as desired (if you know what you are doing).

theme_set(theme_bw()) # change theme for ggplot2
trellis.par.set(theme=theme.mosaic()) # change default color scheme for lattice

knitr::opts_chunk$set(
  tidy=FALSE,     # display code as typed
  size="small")   # slightly smaller font for code
```

## Apple Stock

```{r}
data("AppleStock")
AppleStock <- AppleStock %>%
  mutate(Date = as.Date(Date, format = "%m/%d/%Y"))
head(AppleStock)

gf_point(Price~Date,data=AppleStock) %>%
  gf_refine(scale_x_date(date_breaks = "4 weeks", date_labels = "%b %y")) %>%
  gf_lm(color="darkgreen") %>% 
  gf_labs(title="Apple Stock Prices Spike above $100",y="Price",x="Time") %>% 
  gf_hline(yintercept = 100, linetype = "dashed", alpha=0.7, color="green3", size=1)

ggplot(AppleStock, aes(x = Date, y = Price, fill=Price)) +
  geom_bar(stat = "identity") +
  labs(title = "Apple Prices Hit a High in Mid-October", 
       x = "Date", y = "Price",caption="This data is from 2016 Apple Stock Prices")
```

## April 14th Temps

```{r}
data("April14Temps")
April14TempsWrangled = gather(April14Temps,key="City",value="Temp",2:3)
head(April14TempsWrangled)

gf_line(Temp~Year,data=April14TempsWrangled,color=~City) %>%
  gf_labs(title="San Francisco has More Consistent Temperatures\nthan Des Moines",
  y="Temperature",caption="Data Collected on April 14th of Every Year")

gf_tile(City~Year,data=April14TempsWrangled,fill=~Temp) %>%  
  gf_refine(scale_fill_gradientn(colors = rev(rainbow(2)))) %>%
  gf_labs(title="Des Moines Temps are More Sporadic than\nSan Francisco Temperatures",
  caption="Data Collected on April 14th of Every Year")
```

## Bike Commute

```{r}
data("CityTemps")
CityTempsWrangled = subset(gather(CityTemps,key="City",value="Temp",3:5), Year==2017)
head(CityTempsWrangled)
gf_linerange(Temp+0~Month|City~.,data=CityTempsWrangled,color=~Temp,size = 5) %>% 
  gf_refine(scale_x_continuous(breaks = seq(0, 12, by = 2)), 
            scale_color_gradientn(colors = rev(rainbow(5)))) %>%
  gf_labs(title="Melbourne Has the Lowest Temps in the Middle of the Year",
          caption="Data was collected based on average temperatures in 2017")

gf_line(Temp~Month,color=~City,data=CityTempsWrangled) %>%
  gf_refine(scale_x_continuous(breaks = seq(0, 12, by = 2))) %>%
  gf_labs(title="Moscow has Inconsistent Temperatures throughout 2017")
  
```


